stages:
  - build
  - test
  - package

variables:
  IMAGE_NAME: sieve-pipeline:1.0

build:
  stage: build
  image: eclipse-temurin:21-jdk
  script:
    - apt-get update -y && apt-get install -y ant
    - ant clean
    - ant jar
  artifacts:
    paths:
      - dist/SieveProject.jar
    expire_in: 1 hour

test:
  stage: test
  image: eclipse-temurin:21-jdk
  dependencies:
    - build
  script:
    - echo 100 | java -jar dist/SieveProject.jar > actual_output.txt
    - cat actual_output.txt
    - echo "Comparing with expected_output.txt"
    - diff -u expected_output.txt actual_output.txt
  artifacts:
    paths:
      - actual_output.txt
    expire_in: 1 hour

package:
  stage: package
  image: docker:24.0.2
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
  script:
    - docker build -t $IMAGE_NAME -f Dockerfile.slim .
    - docker image save -o sieve-pipeline.tar $IMAGE_NAME
  artifacts:
    paths:
      - sieve-pipeline.tar
    expire_in: 1 day
